# Generated by Django 3.1.1 on 2023-11-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_selfprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfprofile',
            name='intro',
        ),
        migrations.AddField(
            model_name='selfprofile',
            name='email',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
