# Generated by Django 3.1.1 on 2023-12-03 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20231203_0717'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='User',
        ),
        migrations.AlterModelTable(
            name='user',
            table='test_user',
        ),
    ]
