# Generated by Django 3.1.1 on 2023-11-30 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20231127_1702'),
        ('account', '0003_auto_20231129_1330'),
    ]

    operations = [
    ]
