# Generated by Django 3.1.1 on 2023-12-04 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20231203_0729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
