# Generated by Django 4.2.7 on 2023-11-24 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_auto_20231123_1842'),
        ('landing_page', '0003_alter_post_id'),
    ]

    operations = [
    ]
