# Generated by Django 3.1.1 on 2023-12-09 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0011_auto_20231206_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
