# Generated by Django 3.1.1 on 2023-12-09 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0012_auto_20231209_0242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Landing',
        ),
    ]
