# Generated by Django 3.1.1 on 2023-11-24 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_profile', '0002_auto_20231124_0233'),
        ('self_profile', '0002_auto_20231123_1842'),
    ]

    operations = [
    ]
