# Generated by Django 3.1.1 on 2023-11-27 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_profile', '0003_merge_20231124_2103'),
        ('self_profile', '0005_alter_post_id'),
    ]

    operations = [
    ]
