# Generated by Django 4.2.7 on 2023-11-27 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_profile', '0004_alter_post_id'),
        ('self_profile', '0005_alter_post_id'),
    ]

    operations = [
    ]
