# Generated by Django 3.1.1 on 2023-11-30 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_profile', '0007_merge_20231130_2027'),
        ('self_profile', '0007_auto_20231127_1702'),
    ]

    operations = [
    ]
