# Generated by Django 3.1.1 on 2023-12-02 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_profile', '0008_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
