# Generated by Django 3.1.1 on 2023-12-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_profile', '0009_delete_userprofile'),
        ('self_profile', '0008_merge_20231130_2047'),
    ]

    operations = [
    ]
