# Generated by Django 5.0 on 2023-12-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_profile', '0014_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
