# Generated by Django 3.1.1 on 2023-12-09 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_profile', '0018_auto_20231208_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
