# Generated by Django 4.2.7 on 2023-11-27 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20231123_1842'),
        ('member', '0002_auto_20231124_0233'),
    ]

    operations = [
    ]
