# Generated by Django 3.1.1 on 2023-11-27 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_post_id'),
        ('member', '0003_merge_20231127_0751'),
    ]

    operations = [
    ]
