# Generated by Django 3.1.1 on 2023-12-04 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
