# Generated by Django 3.1.1 on 2023-11-29 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20231129_1330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
