# Generated by Django 3.1.1 on 2023-11-27 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0002_auto_20231124_0233'),
        ('etc', '0002_auto_20231123_1842'),
    ]

    operations = [
    ]
