# Generated by Django 3.1.1 on 2023-11-30 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0006_auto_20231129_1330'),
        ('etc', '0006_merge_0004_alter_post_id_0005_alter_post_id'),
    ]

    operations = [
    ]
