# Generated by Django 5.0 on 2023-12-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0009_merge_20231202_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
