# Generated by Django 4.2.7 on 2023-11-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='board/category_images/%Y/%m/%d/'),
        ),
    ]
