# Generated by Django 4.2.7 on 2023-11-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_merge_20231127_1802'),
        ('board', '0008_alter_category_head_image'),
    ]

    operations = [
    ]
