# Generated by Django 3.1.1 on 2023-11-27 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_category_head_image'),
        ('board', '0007_auto_20231127_1702'),
    ]

    operations = [
    ]
