# Generated by Django 3.1.1 on 2023-11-30 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_merge_20231128_1702'),
        ('board', '0009_auto_20231129_1330'),
    ]

    operations = [
    ]
