# Generated by Django 3.1.1 on 2023-11-30 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_merge_20231130_2027'),
        ('board', '0010_auto_20231127_2235'),
    ]

    operations = [
    ]
