# Generated by Django 3.1.1 on 2023-12-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_merge_20231130_2047'),
        ('board', '0010_auto_20231127_2224'),
    ]

    operations = [
    ]
