# Generated by Django 3.1.1 on 2023-12-09 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('self_profile', '0019_delete_post'),
        ('board', '0014_auto_20231206_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='self_profile.userprofile'),
        ),
    ]
